# Generated by Django 3.1.2 on 2020-10-10 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=40)),
                ('long_name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=400)),
                ('chart_color', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(max_length=5)),
                ('end_time', models.CharField(max_length=5)),
                ('weekday', models.CharField(max_length=10)),
                ('task_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.task_type')),
            ],
        ),
    ]
