# Generated by Django 3.1.2 on 2020-10-10 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_task_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='location',
            field=models.CharField(default='blank', max_length=100),
            preserve_default=False,
        ),
    ]
