# Generated by Django 3.1.2 on 2020-10-10 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_task_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
