# Generated by Django 3.1.2 on 2020-10-10 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_day'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Day',
        ),
        migrations.AlterField(
            model_name='task',
            name='weekday',
            field=models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], default='Monday', max_length=10),
        ),
    ]
