# Generated by Django 3.1.2 on 2020-10-20 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20201011_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='exhibit',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_type',
        ),
    ]
